CREATE TABLE RXS_CT_SHARED_RSS_IMPORT (
	CONTENTID NUMBER(10,0) NOT NULL,
	REVISIONID NUMBER(10,0) NOT NULL,
	RSS_GUID VARCHAR2(255) NULL,
	RSS_SYNCID VARCHAR2(255) NULL,
	RSS_VERSIONID VARCHAR2(50) NULL,
	CONSTRAINT PK_RXS_CT_SHARED_RSS_IMPORT PRIMARY KEY (CONTENTID, REVISIONID)
)


